# Generated by Django 4.0.5 on 2022-06-19 10:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='USER',
            fields=[
                ('USERID', models.AutoField(primary_key=True, serialize=False)),
                ('USERNAME', models.CharField(max_length=200, unique=True)),
                ('USERPASSWORD', models.CharField(max_length=200)),
                ('USERMAIL', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PLAN',
            fields=[
                ('PLANID', models.AutoField(primary_key=True, serialize=False)),
                ('PLANNAME', models.CharField(max_length=200, unique=True)),
                ('CREATED_AT', models.DateTimeField()),
                ('USERID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='financial_planner.user')),
            ],
        ),
        migrations.CreateModel(
            name='INCOMESOURCE',
            fields=[
                ('SOURCEID', models.AutoField(primary_key=True, serialize=False)),
                ('CATEGORY', models.CharField(default='No category', max_length=200)),
                ('SOURCENAME', models.CharField(max_length=200)),
                ('AMOUNT', models.FloatField()),
                ('PLANID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='financial_planner.plan')),
            ],
        ),
    ]
